addSbtPlugin("com.dwijnand"       % "sbt-travisci"   % "1.1.3")
addSbtPlugin("com.geirsson"       % "sbt-scalafmt"   % "1.6.0-RC4")
addSbtPlugin("com.geirsson"       % "sbt-ci-release" % "1.2.1")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"        % "0.3.3")
addSbtPlugin("org.tpolecat"       % "tut-plugin"     % "0.6.10")
addSbtPlugin("com.eed3si9n"       % "sbt-buildinfo"  % "0.9.0")
